### ISSUE TITLE
Enable hCore editor pane multi-tab operations

### ISSUE THREAD

**Issue by ndebuhr** [hashintel/engine#1]
Using [Code Server](https://github.com/cdr/code-server) as my IDE (in-browser and Monaco-based, like hCore), I constantly use the tab operations like Close All.  Please see the image below for more examples.  Without that option in the hCore editor pane and without documented shortcuts https://docs.hash.ai/core/extra/shortcuts, I'm finding some editor pane operation to be a bit cumbersome/slow.  For example, closing 10 tabs appears to require clicking each of the "X" close buttons.  I'm opening this issue as a feature request - whatever the implementation, improved user experience around multi-tab operations would be appreciated.

<img width="269" alt="Screen Shot 2020-11-01 at 5 07 51 PM" src="https://user-images.githubusercontent.com/14877920/97819820-2a7ddc00-1c68-11eb-8b22-9d3643edaabf.png">

**Comment by nonparibus** [comment]
Hi Neal, thanks for flagging this disparity. We're now tracking this internally as CORE-964 and hope to have a rough ETA shortly.

**Comment by nonparibus** [comment]
Just a quick update: we're planning to address this in our next release. 👍  We'll resolve this issue when it's in!

**Comment by francolaiuppa** [comment]
Hello @ndebuhr, we have great news! 🎉  The feature finally arrived in production, hoping it'll make your life easier. 
I'm going to resolve this issue now, but feel free to forward any feedback you have. Thanks
